<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\SharedKernel\src\SharedKernel.csproj" />
    <PackageReference Include="Trellis.ResourceNaming.Azure" />
    <PackageReference Include="Trellis.Mediator" />
  </ItemGroup>
</Project>
