<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <IsAotCompatible>false</IsAotCompatible>
    <EnableAotAnalyzer>false</EnableAotAnalyzer>
    <EnableTrimAnalyzer>false</EnableTrimAnalyzer>
    <RootNamespace>ProjectTrackerTemplate.Members.Api</RootNamespace>
    <AssemblyName>ProjectTrackerTemplate.Members.Api</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Acl\src\Members.Acl.csproj" />
    <ProjectReference Include="..\..\Application\src\Members.Application.csproj" />
    <ProjectReference Include="..\..\Domain\src\Members.Domain.csproj" />
    <ProjectReference Include="..\..\..\ServiceDefaults\src\ServiceDefaults.csproj" />
    <ProjectReference Include="..\..\..\SharedKernel\src\SharedKernel.csproj" />
    <Using Include="ProjectTrackerTemplate.SharedKernel" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" />
    <PackageReference Include="Microsoft.IdentityModel.Protocols.OpenIdConnect" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" />
    <PackageReference Include="Mediator.Abstractions" />
    <PackageReference Include="Azure.Identity" />
    <!--#if (UseApiVersioning)-->
    <PackageReference Include="Asp.Versioning.OpenApi" />
    <!--#endif-->
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Scalar.AspNetCore" />
    <PackageReference Include="Scalar.AspNetCore.Microsoft" />
    <PackageReference Include="Trellis.Asp" />
    <!--#if (UseApiVersioning)-->
    <PackageReference Include="Trellis.Asp.ApiVersioning" />
    <!--#endif-->
    <PackageReference Include="Trellis.Asp.Idempotency.Cosmos" />
    <PackageReference Include="Trellis.ServiceDefaults" />
    <PackageReference Include="Trellis.Authorization" />
    <PackageReference Include="Trellis.Core" />
    <!--#if (UseApiVersioning)-->
    <PackageReference Include="Trellis.ServiceLevelIndicators.Asp.ApiVersioning" />
    <!--#endif-->
    <PackageReference Include="Trellis.Microservices.AspNetCore" />
  </ItemGroup>

</Project>
